import {loadTimeData} from '//resources/js/load_time_data.js';
loadTimeData.data = {
    "addContext": "Add a tab and more",
    "addContextTitle": "Add a tab or file to your search, and also use a tool",
    "addImage": "Add image",
    "addLinkTitle": "Add shortcut",
    "addTab": "Most recent tabs",
    "askAboutThisTab": "Ask Google about previous tab",
    "askAboutThisTabAriaLabel": "Ask Google about previous tab: $1",
    "audioError": "Please check your microphone.",
    "backgroundColor": "#202020",
    "backgroundImageUrl": "",
    "browserPromoCompletedLimit": 2,
    "browserPromoLimit": 10,
    "browserPromoType": "setuplist",
    "calendarModuleDismissHours": "12",
    "charTypedToPaintMetricName": "",
    "close": "Close",
    "colorPickerLabel": "Custom colour",
    "composeCreateImagePlaceholder": "Describe your image",
    "composeDeepSearchPlaceholder": "Research anything",
    "composeboxAttachmentFileTypes": ".pdf,application/pdf",
    "composeboxCancelButtonTitle": "Dismiss",
    "composeboxCancelButtonTitleInput": "Clear",
    "composeboxCloseByClickOutside": true,
    "composeboxCloseByEscape": true,
    "composeboxDeleteFileTitle": "$1 press enter to delete file",
    "composeboxFileMaxCount": 1,
    "composeboxFileMaxSize": 200000000,
    "composeboxFileUploadCompleteText": "File upload complete",
    "composeboxFileUploadExpired": "File upload has expired and been removed.",
    "composeboxFileUploadFailed": "Unexpected error, file upload failed.",
    "composeboxFileUploadImageProcessingError": "Can't upload. Failed to process image file.",
    "composeboxFileUploadInvalidEmptySize": "Can't upload. File appears to be empty.",
    "composeboxFileUploadInvalidTooLarge": "Can't upload. File exceeds maximum supported size.",
    "composeboxFileUploadStartedText": "Uploading file",
    "composeboxFileUploadValidationFailed": "Can't upload. File upload failed validation checks.",
    "composeboxImageFileTypes": "image/*",
    "composeboxImageUploadButtonTitle": "Upload an image",
    "composeboxPdfUploadButtonTitle": "Upload a PDF",
    "composeboxPlaceholderText": "Ask AI Mode",
    "composeboxShowContextMenu": true,
    "composeboxShowContextMenuDescription": true,
    "composeboxShowContextMenuTabPreviews": false,
    "composeboxShowCreateImageButton": false,
    "composeboxShowDeepSearchButton": false,
    "composeboxShowImageSuggest": false,
    "composeboxShowPdfUpload": true,
    "composeboxShowRecentTabChip": false,
    "composeboxShowSubmit": true,
    "composeboxShowTypedSuggest": false,
    "composeboxShowZps": true,
    "composeboxSmartComposeEnabled": true,
    "composeboxSmartComposeTabTitle": "Tab",
    "composeboxSmartComposeTitle": "Press Tab to accept this suggestion",
    "composeboxSubmitButtonTitle": "Send",
    "controlledSettingPolicy": "This setting is managed by your administrator.",
    "copyLink": "Copy link",
    "createImages": "Create images",
    "customizeButton": "Customise Chromium",
    "customizeThisPage": "Customise this page",
    "customizeThisPageWallpaperSearch": "Customise this page with AI",
    "deepSearch": "Deep Search",
    "details": "Details",
    "disableModuleToastMessage": "You won't see $1 on this page again",
    "dismissButton": "Dismiss",
    "dismissModuleToastMessage": "$1 hidden",
    "doneButton": "Done",
    "doodleLink": "Doodle Link",
    "editLinkTitle": "Edit shortcut",
    "email": "Email",
    "enableCsbMotionTweaks": false,
    "enableThumbnailSizingTweaks": false,
    "enterpriseShortcutSubtitle": "This setting is managed by your organisation",
    "facebook": "Facebook",
    "fileSuggestionDismissHours": "12",
    "fontfamily": "'Segoe UI', Tahoma, sans-serif",
    "fontfamilyMd": "'Segoe UI', Tahoma, sans-serif",
    "fontsize": "75%",
    "footerEnabled": true,
    "forceHideEllipsis": false,
    "googleBaseUrl": "https://www.google.com/",
    "hueSliderAriaLabel": "Hue slider from $1 to $2",
    "hueSliderTitle": "Colour picker",
    "invalidUrl": "Type a valid URL",
    "isLensSearchbox": false,
    "isTopChromeSearchbox": false,
    "language": "en",
    "languageError": "Voice search in your language is not available.",
    "learnMore": "Learn more",
    "learnMoreA11yLabel": "Learn more about using a microphone",
    "lensSearchButtonLabel": "Select region of screen for follow-up",
    "lensSearchUploadDialogCloseButtonLabel": "Close",
    "lensSearchUploadDialogDragDropTitle": "Drop an image here",
    "lensSearchUploadDialogDragTitle": "Drag an image here or",
    "lensSearchUploadDialogErrorFileSize": "Can't upload. Use an image smaller than 20 MB.",
    "lensSearchUploadDialogErrorFileType": "Can't upload. Use an image in one of these formats: .jpg, .gif, .png, .bmp, .tif or .webp",
    "lensSearchUploadDialogErrorMultipleFiles": "Can't search multiple images. Add one image at a time.",
    "lensSearchUploadDialogErrorMultipleUrls": "Can't search multiple images. Add one image at a time.",
    "lensSearchUploadDialogLoadingText": "Uploading…",
    "lensSearchUploadDialogOfflineButtonLabel": "Try again",
    "lensSearchUploadDialogOfflineSubtitleText": "Please check your Internet connection and try again",
    "lensSearchUploadDialogOfflineText": "No network connection",
    "lensSearchUploadDialogOrText": "OR",
    "lensSearchUploadDialogSearchButtonLabel": "Search",
    "lensSearchUploadDialogTextPlaceholder": "Paste image link",
    "lensSearchUploadDialogTitle": "Search any image with Lens",
    "lensSearchUploadDialogUploadFileTitle": "upload a file",
    "lensSearchUploadDialogValidationErrorConformance": "Can't use this link. Check for typos or use another link to try again.",
    "lensSearchUploadDialogValidationErrorScheme": "Can't use this link. Check that your link starts with 'http://' or 'https://' to try again.",
    "linkAddedMsg": "Shortcut added",
    "linkCancel": "Cancel",
    "linkCantCreate": "Can't create shortcut",
    "linkCantEdit": "Can't edit shortcut",
    "linkDone": "Done",
    "linkEditedMsg": "Shortcut edited",
    "linkRemove": "Remove",
    "linkRemovedMsg": "Shortcut removed",
    "listening": "Listening…",
    "logoEnabled": true,
    "maxTilesBeforeShowMore": 5,
    "menu": "Menu",
    "microsoftModuleEnabled": false,
    "middleSlotPromoDismissalEnabled": true,
    "middleSlotPromoEnabled": true,
    "mobilePromoDescription": "Download Chrome for iOS to access your tabs, bookmarks and passwords on your phone.",
    "mobilePromoEnabled": true,
    "mobilePromoHeader": "Get Chrome on your mobile device",
    "mobilePromoQrCode": "Scan QR Code",
    "moduleGoogleCalendarInfo": "You're seeing your calendar to help you easily navigate to your next event in Google Calendar.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "moduleHeaderMoreActionsMenu": "More actions",
    "moduleInfoButtonTitle": "About this card",
    "modulesCalendarInProgress": "In progress",
    "modulesCalendarInXHr": "In $1 hr",
    "modulesCalendarInXMin": "In $1 min",
    "modulesCalendarJoinMeetingButtonAcc": "Join meeting $1",
    "modulesCalendarJoinMeetingButtonText": "Join meeting",
    "modulesCalendarSeeMore": "See more",
    "modulesCalendarSeeMoreAcc": "See more meetings on your Calendar",
    "modulesCustomizeButtonText": "Customise cards",
    "modulesDisableButtonText": "Never show $1",
    "modulesDisableButtonTextV2": "Don't show $1",
    "modulesDisableToastMessage": "You won't see $1 again",
    "modulesDismissButtonText": "Hide $1",
    "modulesDismissForDaysButtonText": "Hide for $1 days",
    "modulesDismissForHoursButtonText": "Hide for $1 hours",
    "modulesDragAndDropEnabled": false,
    "modulesDriveDisableButtonText": "Never show Drive files",
    "modulesDriveDisableButtonTextV2": "Don't show Drive",
    "modulesDriveInfo": "You’re seeing suggested files to help you easily get back to your most recent activity in Google Drive.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "modulesDriveMoreActionsButtonText": "More actions for Google Drive files",
    "modulesDriveSentence": "Google Drive",
    "modulesDriveTitle": "Google Drive",
    "modulesDriveTitleV2": "Google Drive",
    "modulesDummyLower": "this module",
    "modulesDummyTitle": "Super Duper Module",
    "modulesEnabled": false,
    "modulesFilesSentence": "Files",
    "modulesGoogleCalendarDisableButtonText": "Don't show Google Calendar",
    "modulesGoogleCalendarDisableToastMessage": "You won't see Google Calendar on this page again",
    "modulesGoogleCalendarDismissToastMessage": "Google Calendar hidden",
    "modulesGoogleCalendarMoreActions": "More actions for Google Calendar",
    "modulesGoogleCalendarTitle": "Google Calendar",
    "modulesHistoryDoneButton": "Mark as done and hide",
    "modulesHistoryResumeBrowsingForTitle": "Resume browsing for $1",
    "modulesHistoryResumeBrowsingTitle": "Resume browsing",
    "modulesHistoryWithDiscountInfo": "You’re seeing suggested searches and shopping discounts that might interest you based on your recent activity.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from this card at any time or see more options in Customise Chrome.",
    "modulesJourneyDisable": "this card",
    "modulesJourneysBookmarked": "Bookmarked",
    "modulesJourneysDismissButton": "No longer interested",
    "modulesJourneysInfo": "You’re seeing pages you've visited and suggested searches to help you easily get back to your most recent activity.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "modulesJourneysOpenAllInNewTabGroupButtonText": "Open all in new tab group",
    "modulesJourneysSearchSuggAcc": "Search for $1",
    "modulesJourneysShowAll": "Show all",
    "modulesJourneysShowAllAcc": "Show all searches for $1",
    "modulesJourneysShowAllButton": "Open in side panel",
    "modulesKaleidoscopeTitle": "Top picks for you",
    "modulesLoadEnabled": false,
    "modulesLoadTimeout": 3000,
    "modulesMaxColumnCount": 3,
    "modulesMicrosoftAuthDisable": "Don't show this card",
    "modulesMicrosoftAuthDismiss": "Hide for 12 hours",
    "modulesMicrosoftAuthHeading": "See your Outlook calendar, and SharePoint and OneDrive files",
    "modulesMicrosoftAuthName": "Microsoft authentication",
    "modulesMicrosoftAuthSignIn": "Sign in with Microsoft",
    "modulesMicrosoftAuthSubheading": "Easily access recent documents and upcoming calendar events",
    "modulesMicrosoftFilesDisableButtonText": "Don't show SharePoint and OneDrive files",
    "modulesMicrosoftFilesInfo": "You're seeing suggested files to help you easily get back to your most recent activity in Microsoft SharePoint and OneDrive.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "modulesMicrosoftFilesName": "SharePoint and OneDrive files",
    "modulesMicrosoftSignOutButtonText": "Sign out of Microsoft",
    "modulesMoreActions": "More actions for $1",
    "modulesMostRelevantTabResumptionDismissAll": "Hide these tabs",
    "modulesMostRelevantTabResumptionFrequentlyVisited": "You visit often",
    "modulesMostRelevantTabResumptionMostRecent": "Your most recent tab",
    "modulesMostRelevantTabResumptionSeeMore": "See more",
    "modulesMostRelevantTabResumptionTitle": "Continue with these tabs",
    "modulesMostRelevantTabResumptionVisitedXAgo": "You visited",
    "modulesOutlookCalendarDisableButtonText": "Don't show Outlook Calendar",
    "modulesOutlookCalendarDismissToastMessage": "Outlook calendar hidden",
    "modulesOutlookCalendarInfo": "You're seeing your calendar to help you easily navigate to your next event in Outlook Calendar.\n       \u003Cbr>\n       \u003Cbr>\n       You can manage settings from the card menu or see more options in Customise Chrome.",
    "modulesOutlookCalendarTitle": "Outlook calendar",
    "modulesReloadable": false,
    "modulesSetupListDisableToastMessage": "You won't see $1 on this page again",
    "modulesSetupListDismissToastMessage": "$1 hidden",
    "modulesSetupListInfo": "You're seeing suggestions on how to personalise Chrome and make it more powerful for your daily needs.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "modulesSetupListTitle": "Make Chromium yours",
    "modulesTabGroupsCreateNewTabGroup": "Create new tab group",
    "modulesTabGroupsDisableToastMessage": "You won't see tab groups on this page again",
    "modulesTabGroupsDismissToastMessage": "Tab groups hidden",
    "modulesTabGroupsInfo": "You're seeing your recently used tab groups to help you easily pick up where you left off.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "modulesTabGroupsTitle": "Your tab groups",
    "modulesTabGroupsZeroStateText": "You can group tabs to keep related pages together and saved across your devices",
    "modulesTabGroupsZeroStateTitle": "Stay organised with tab groups",
    "modulesTabResumptionDevicePrefix": "From your",
    "modulesTabResumptionDismissButton": "No longer interested",
    "modulesTabResumptionInfo": "You're seeing tabs from other devices to help you get back to your most recent activity easily.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customise Chrome.",
    "modulesTabResumptionMultiDismiss": "Tabs hidden",
    "modulesTabResumptionSingleDismiss": "Tab hidden",
    "modulesTabResumptionTitle": "Continue with these tabs",
    "modulesTasksInfo": "You're seeing this item based on your previous activity using Google services. You can see your data, delete it and change your settings at \u003Ca href=\"https://myactivity.google.com/\" target=\"_blank\">myactivity.google.com\u003C/a>.\n        \u003Cbr>\n        \u003Cbr>\n        Learn about the data that Google collects and why at \u003Ca href=\"https://policies.google.com/\" target=\"_blank\">policies.google.com\u003C/a>.",
    "modulesTasksInfoClose": "Close",
    "modulesTasksInfoTitle": "About this card",
    "modulesThisTypeOfCardText": "this type of card",
    "mostRelevantTabResumptionAllowFaviconServerFallback": true,
    "mostRelevantTabResumptionModuleFallbackToHost": true,
    "multipleLoadedModulesMaxModuleInstanceCount": 2,
    "nameField": "Name",
    "navigationStartTime": 1.761118773729584e+12,
    "networkError": "No Internet connection.",
    "noTranslation": "Didn't get that.",
    "noVoice": "Please check your microphone and audio levels.",
    "ntpNextFeaturesEnabled": false,
    "ntpRealboxNextEnabled": true,
    "ok": "OK",
    "oneGoogleBarEnabled": true,
    "otherError": "Unknown error.",
    "permissionError": "Voice search has been turned off.",
    "preconnectStartTimeThreshold": 100,
    "prefetchStartTimeThreshold": 300,
    "prefetchTriggerEnabled": true,
    "prerenderOnPressEnabled": true,
    "realboxLayoutMode": "TallBottomContext",
    "removeSuggestion": "Remove suggestion",
    "reportMetrics": false,
    "restoreDefaultEnterpriseShortcuts": "Restore organisation shortcuts",
    "restoreDefaultLinks": "Restore default shortcuts",
    "restoreThumbnailsShort": "Restore all",
    "resultChangedToPaintMetricName": "",
    "searchBoxHint": "Search Google or type a URL",
    "searchBoxHintMultimodal": "Add to your search",
    "searchBoxPlaceholder": "Ask Google",
    "searchboxComposeButtonText": "AI Mode",
    "searchboxComposeButtonTitle": "Ask Google AI Mode",
    "searchboxComposePlaceholder": "Ask AI Mode",
    "searchboxCr23SteadyStateShadow": false,
    "searchboxCr23Theming": false,
    "searchboxCyclingPlaceholders": true,
    "searchboxDefaultIcon": "//resources/cr_components/searchbox/icons/search_cr23.svg",
    "searchboxLensSearch": true,
    "searchboxLensVariations": "COrjygE",
    "searchboxMatchSearchboxTheme": false,
    "searchboxSeparator": " - ",
    "searchboxShowComposeAnimation": false,
    "searchboxShowComposeEntrypoint": true,
    "searchboxShowComposebox": true,
    "searchboxThumbnailLabel": "Your Google Lens selection. Press enter or backspace to delete your Google Lens selection",
    "searchboxVoiceSearch": true,
    "setupListModuleDismissDays": "7",
    "shareDoodle": "Share Doodle",
    "shortcutAlreadyExists": "Shortcut already exists",
    "shortcutMoreActions": "More actions for $1 shortcut",
    "shortcutsEnabled": true,
    "showMore": "Show more",
    "speak": "Speak now",
    "suggestionActivityLink": "Suggestions based on your \u003Ca target=\"_blank\" href=\"https://myactivity.google.com/activitycontrols?settings=search&utm_source=aim&utm_campaign=aim_str\">Google activity\u003C/a>",
    "tabGroupsModuleDismissHours": "12",
    "textdirection": "ltr",
    "themeCreatedBy": "Theme created by",
    "themeManagedDialogBody": "Your administrator has set a default theme which cannot be changed.",
    "themeManagedDialogTitle": "Theme is set by your organisation",
    "title": "New tab",
    "tryAgain": "Try again",
    "twitter": "Twitter",
    "undo": "Undo",
    "undoDescription": "Press Ctrl+Z to undo",
    "undoDismissPromoButtonToast": "You won't see this specific message again",
    "uploadFile": "Add file",
    "urlField": "URL",
    "viewLink": "Details",
    "viewLinkTitle": "Shortcut",
    "voiceSearchButtonLabel": "Search by voice",
    "waitToLoadModules": false,
    "waiting": "Waiting…",
    "wallpaperSearchButton": "Create theme with AI",
    "wallpaperSearchButtonAnimationEnabled": false,
    "wallpaperSearchButtonEnabled": false,
    "wallpaperSearchButtonHideCondition": 1,
    "webstoreThemesToastButtonText": "Find themes",
    "webstoreThemesToastMessage": "You can find older colours in the Chrome Web Store"
};
